# Generated by Django 5.2.5 on 2025-08-06 09:40

from django.db import migrations

from hierarkey.utils import CleanHierarkeyDuplicates


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        CleanHierarkeyDuplicates("GlobalSettings_SettingsStore"),
        CleanHierarkeyDuplicates("Organization_SettingsStore"),
        CleanHierarkeyDuplicates("User_SettingsStore"),
        migrations.AlterUniqueTogether(
            name="globalsettings_settingsstore",
            unique_together={("key",)},
        ),
        migrations.AlterUniqueTogether(
            name="organization_settingsstore",
            unique_together={("object", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="user_settingsstore",
            unique_together={("object", "key")},
        ),
    ]
