# Generated by Django 5.2.3 on 2025-06-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalsettings_settingsstore',
            unique_together={('key',)},
        ),
        migrations.AlterUniqueTogether(
            name='organization_settingsstore',
            unique_together={('object', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='user_settingsstore',
            unique_together={('object', 'key')},
        ),
    ]
